apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
  labels:
    app: redis-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander:latest
        ports:
        - containerPort: 8081
        env:
        - name: REDIS_HOSTS 
          valueFrom:
            configMapKeyRef:
              name: redis-commander-config
              key: HOSTS 
        - name: REDIS_PASSWORD 
          valueFrom:
            configMapKeyRef:
              name: redis-commander-config
              key: PASSWORD   
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-commander-config
data:
  HOSTS: "redis-service.default.svc.cluster.local:6379"
  PASSWORD: "lofasz" 

--- 
apiVersion: v1
kind: Service
metadata:
  name: redis-commander-service
  labels:
    app: redis
spec:
  type: LoadBalancer 
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30001 
  selector:
    app: redis-commander