apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
      - name: redis-commander
        image: rediscommander/redis-commander
        ports:
        - containerPort: 5540
        env:
        - name: HOST
          value: "0.0.0.0"
        - name: REDIS_HOST 
          valueFrom:
            configMapKeyRef:
              name: redis-commander-config
              key: HOSTS 
        - name: REDIS_PASSWORD
          value: "password"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-commander-config
data:
  #HOSTS: "redis://password@redis-db-service.default.svc.cluster.local:6379"
  HOSTS: "redis-db-service.default.svc.cluster.local"
  PASSWORD: "password" 
--- 
apiVersion: v1
kind: Service
metadata:
  name: redis-commander-service
  labels:
    app: redis-commander
spec:
  selector:
    app: redis-commander
  type: NodePort # LoadBalancer
  ports:
  - protocol: TCP
    port: 8081        # Change this to 8081
    targetPort: 8081   # Make sure the target port matches the port Redis Commander is listening on
    nodePort: 30000